FROM bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8

COPY *.jar /opt/hadoop/applications/

ENV JAR_FILEPATH="/opt/hadoop/applications/PageRankInitializer.jar"
ENV CLASS_TO_RUN="PageRankInitializer"
ENV PARAMS="/output /output_pagerank"

ADD run.sh /run.sh
RUN chmod a+x /run.sh

CMD ["/run.sh"]
